services:
  odoo:
    image: odoo:17
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:8069:8069"
    volumes:
      - data:/var/lib/odoo
      - ./addons:/mnt/extra-addons

  postgres:
    image: postgres:16-alpine
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data/pgdata

volumes:
  data:
  db:
